export const GET_SCORES_REQUEST = 'GET_SCORES_REQUEST'
export const GET_SCORES_SUCCESS = 'GET_SCORES_SECCESS'
export const GET_SCORES_ERROR = 'GET_SCORES_ERROR'
export const CLEAR_SCORES = 'CLEAR_SCORES'
